In [ ]:
import pandas as pd
import constantes

#Verifica se a pasta existe; se não, cria.
os.makedirs('db', exist_ok=True)

Salvar os estabelecimentos em csv

In [46]:
df_mercado = pd.DataFrame(constantes.NOMES_MERCADOS, columns = ['Estabelecimento'])
df_mercado

                Estabelecimento
0                       Azevedo
1                    Bh Atacado
2                     Bh Varejo
3                     Bom Preço
4                        Caribé
5                      Caribé 2
6            Cestão Da Economia
7   Cestão Da Economia (Bairro)
8                         Gordo
9                        Kamila
10                   Mart Minas
11                  Montalvânia
12                Montalvânia 2
13                     Nacional
14                    Pag Pouco
15                        Porto
16                  Preço Baixo
17                Preço Baixo 2
18      Pão De Mel (Rodoviária)
19                        Rocha
20                   Super Maar
21                  Terra Norte
22             União Mega Feira

In [47]:
df_posto = pd.DataFrame(constantes.NOMES_POSTOS, columns = ['Estabelecimento'])
df_posto

                  Estabelecimento
0                      Posto (1l)
1             Posto Alvorada (1l)
2          Posto Alvorada II (1l)
3                   Posto BH (1l)
4            Posto Carrancas (1l)
5              Posto Central (1l)
6      Posto Jb Combustiveis (1l)
7   Posto Jb Combustiveis II (1l)
8               Posto Joelma (1l)
9          Posto Joelma (BH) (1l)
10            Posto Oliveira (1l)
11         Posto Oliveira II (1l)
12          Posto Paraguassú (1l)
13            Posto Pioneiro (1l)
14                 Posto Vip (1l)
15         Posto Itapiraçaba (1l)
16   Posto Oliveira II / Vip (1l)

In [48]:
df_mercado['tipo_estabelecimento'] = 'SUPERMERCADO'
df_posto['tipo_estabelecimento'] = 'POSTO_COMBUSTIVEL'

In [49]:
df_estabelecimento = pd.concat([df_mercado, df_posto], ignore_index=True)
df_estabelecimento

                  Estabelecimento tipo_estabelecimento
0                         Azevedo         SUPERMERCADO
1                      Bh Atacado         SUPERMERCADO
2                       Bh Varejo         SUPERMERCADO
3                       Bom Preço         SUPERMERCADO
4                          Caribé         SUPERMERCADO
5                        Caribé 2         SUPERMERCADO
6              Cestão Da Economia         SUPERMERCADO
7     Cestão Da Economia (Bairro)         SUPERMERCADO
8                           Gordo         SUPERMERCADO
9                          Kamila         SUPERMERCADO
10                     Mart Minas         SUPERMERCADO
11                    Montalvânia         SUPERMERCADO
12                  Montalvânia 2         SUPERMERCADO
13                       Nacional         SUPERMERCADO
14                      Pag Pouco         SUPERMERCADO
15                          Porto         SUPERMERCADO
16                    Preço Baixo         SUPERMERCADO
17                  Preço Baixo 2         SUPERMERCADO
18        Pão De Mel (Rodoviária)         SUPERMERCADO
19                          Rocha         SUPERMERCADO
20                     Super Maar         SUPERMERCADO
21                    Terra Norte         SUPERMERCADO
22               União Mega Feira         SUPERMERCADO
23                     Posto (1l)    POSTO_COMBUSTIVEL
24            Posto Alvorada (1l)    POSTO_COMBUSTIVEL
25         Posto Alvorada II (1l)    POSTO_COMBUSTIVEL
26                  Posto BH (1l)    POSTO_COMBUSTIVEL
27           Posto Carrancas (1l)    POSTO_COMBUSTIVEL
28             Posto Central (1l)    POSTO_COMBUSTIVEL
29     Posto Jb Combustiveis (1l)    POSTO_COMBUSTIVEL
30  Posto Jb Combustiveis II (1l)    POSTO_COMBUSTIVEL
31              Posto Joelma (1l)    POSTO_COMBUSTIVEL
32         Posto Joelma (BH) (1l)    POSTO_COMBUSTIVEL
33            Posto Oliveira (1l)    POSTO_COMBUSTIVEL
34         Posto Oliveira II (1l)    POSTO_COMBUSTIVEL
35          Posto Paraguassú (1l)    POSTO_COMBUSTIVEL
36            Posto Pioneiro (1l)    POSTO_COMBUSTIVEL
37                 Posto Vip (1l)    POSTO_COMBUSTIVEL
38         Posto Itapiraçaba (1l)    POSTO_COMBUSTIVEL
39   Posto Oliveira II / Vip (1l)    POSTO_COMBUSTIVEL

In [50]:
df_estabelecimento.sort_values(by='Estabelecimento')
df_estabelecimento

                  Estabelecimento tipo_estabelecimento
0                         Azevedo         SUPERMERCADO
1                      Bh Atacado         SUPERMERCADO
2                       Bh Varejo         SUPERMERCADO
3                       Bom Preço         SUPERMERCADO
4                          Caribé         SUPERMERCADO
5                        Caribé 2         SUPERMERCADO
6              Cestão Da Economia         SUPERMERCADO
7     Cestão Da Economia (Bairro)         SUPERMERCADO
8                           Gordo         SUPERMERCADO
9                          Kamila         SUPERMERCADO
10                     Mart Minas         SUPERMERCADO
11                    Montalvânia         SUPERMERCADO
12                  Montalvânia 2         SUPERMERCADO
13                       Nacional         SUPERMERCADO
14                      Pag Pouco         SUPERMERCADO
15                          Porto         SUPERMERCADO
16                    Preço Baixo         SUPERMERCADO
17                  Preço Baixo 2         SUPERMERCADO
18        Pão De Mel (Rodoviária)         SUPERMERCADO
19                          Rocha         SUPERMERCADO
20                     Super Maar         SUPERMERCADO
21                    Terra Norte         SUPERMERCADO
22               União Mega Feira         SUPERMERCADO
23                     Posto (1l)    POSTO_COMBUSTIVEL
24            Posto Alvorada (1l)    POSTO_COMBUSTIVEL
25         Posto Alvorada II (1l)    POSTO_COMBUSTIVEL
26                  Posto BH (1l)    POSTO_COMBUSTIVEL
27           Posto Carrancas (1l)    POSTO_COMBUSTIVEL
28             Posto Central (1l)    POSTO_COMBUSTIVEL
29     Posto Jb Combustiveis (1l)    POSTO_COMBUSTIVEL
30  Posto Jb Combustiveis II (1l)    POSTO_COMBUSTIVEL
31              Posto Joelma (1l)    POSTO_COMBUSTIVEL
32         Posto Joelma (BH) (1l)    POSTO_COMBUSTIVEL
33            Posto Oliveira (1l)    POSTO_COMBUSTIVEL
34         Posto Oliveira II (1l)    POSTO_COMBUSTIVEL
35          Posto Paraguassú (1l)    POSTO_COMBUSTIVEL
36            Posto Pioneiro (1l)    POSTO_COMBUSTIVEL
37                 Posto Vip (1l)    POSTO_COMBUSTIVEL
38         Posto Itapiraçaba (1l)    POSTO_COMBUSTIVEL
39   Posto Oliveira II / Vip (1l)    POSTO_COMBUSTIVEL

In [51]:
df_estabelecimento.to_csv('db/estabelecimentos.csv', index=False)

salvar categorias_produtos em csv

In [24]:
df_categoria_produto = pd.DataFrame(constantes.NOMES_PRODUTOS, columns=['Produto'])
df_categoria_produto.to_csv('db/categorias_produtos.csv', index=False)

Salvar as marcas em csv

In [26]:
df_marcas = pd.DataFrame(constantes.NOMES_MARCAS, columns=['nome'])
df_marcas.to_csv('db/marcas.csv', index=False)